# Uncomment this line to define a global platform for your project
platform :ios, '11.0'

target 'iTransmission' do
	pod 'Firebase/Core'
	pod 'Fabric'
	pod 'TwitterKit'
	pod 'LGSideMenuController'
end
